version: '3'

networks:
  fast_api_net:
    driver: bridge
  redis_net:
    driver: bridge

services:
  nginx:
    restart: always
    image: nginx:1.23-alpine
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fast_api_net
  web:
    restart: always
    build: .
    command: sh -c "uvicorn main:app --reload --port=8001  --host=0.0.0.0"
    networks:
      - fast_api_net
      - redis_net
    volumes:
      - ./app:/app
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - redis_net




  